name: "Build and Deploy"
on:
  ## Events from external actor, or from code pushed (includes tags pushed)
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    # In the future it would be good to run the tests on amd64 and arm64
    # This will require one of these:
    # https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
    # https://github.com/marketplace/actions/arm-runner
    runs-on: ubuntu-latest
    steps:
      - name: check ref
        run: echo ${{ github.ref }}
      - name: only if on a tag
        if: github.ref_type == 'tag'
        run: echo TAG
      - name: only if on the main branch
        if: contains(github.ref, 'refs/head/main')
        run: echo MAIN
      - name: only if on the main branch OR a tag
        if: contains('refs/head/main', github.ref) || github.ref_type == 'tag'
        run: echo MAIN
