---
name: Updatecli

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  updatecli:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Apply
        uses: updatecli/updatecli-action@v1
        with:
          command: apply
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
