---
name: Updatecli

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  ## Events from external actor, or from code pushed (includes tags pushed)
  push:
  pull_request:
jobs:
  updatecli:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      ## Ensure that the updatecli configuration are valid without waiting for the daily execution from the workflow "Updatecli"
      - name: Diff
        uses: updatecli/updatecli-action@v1
        ## Check the updatecli syntax on each code change
        if: github.event_name != 'schedule'
        with:
          command: diff
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply
        ## Update Dependencies Only Once a day
        if: github.event_name == 'schedule'
        uses: updatecli/updatecli-action@v1
        with:
          command: apply
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
